# My project

This is the link to Github: https://github.com/adamrkenny/ec-a01

In [1]:
import pandas as pd

# load data
data_file = 'classdata-abc.csv'
data = pd.read_csv(data_file)

# view data
data

      m1 lecture
0     67       a
1     59       a
2    100       a
3     81       a
4     80       a
..   ...     ...
159   53       c
160  100       c
161   57       c
162   74       c
163   95       c

[164 rows x 2 columns]